---
name: configuration
brief: physical (dis)similarity and spatiotemporal connectedness
full: TODO
values:
  - abbrev: UNI
    name: Uniplex
    brief: individual instance
  - abbrev: DUP
    name: Duplex
    brief: pair of instances
  - abbrev: DCT
    name: Discrete
    brief: many similar instances
  - abbrev: AGG
    name: aggregative
    brief: collection of dissimilar instances
  - abbrev: SEG
    name: segmentative
    brief: close or contiguous group of similar instances
  - abbrev: CPN
    name: componential
    brief: close or contiguous group of dissimilar instances
  - abbrev: COH
    name: coherent
    brief: connected collection of similar instances
  - abbrev: CST
    name: composite
    brief: connected collection of dissimilar instances
  - abbrev: MLT
    name: multiform
    brief: borderline or questionable instance
...
