---
name: Configuration
brief: describes the physical (dis)similarity and spatiotemporal connectedness of the item(s) named by the stem.
values:
  - name: Uniplex
    abbrev: UNI
    brief: marks an individual instance.  
  - name: Duplex
    abbrev: DUP
    brief: indicates a pair of instances.  
  - name: Discrete
    abbrev: DCT
    brief: discrete refers to a group of several similar instances.  
  - name: Aggregative
    abbrev: AGG
    brief: denotes a collection of dissimilar instances.  
  - name: Segmentative
    abbrev: SEG
    brief: refers to a close or contiguous grouping of similar instances.  
  - name: Componential
    abbrev: CPN
    brief: denotes a close or contiguous collection of dissimilar instances.  
  - name: Coherent
    abbrev: COH
    brief: indicates connected collection of similar instances.  
  - name: Composite
    abbrev: CST
    brief: refers to a connected collection of dissimilar instances.  
  - name: Multiform
    abbrev: MLT
    brief: denotes a borderline or questionable instance of a stem.
...
